### ISSUE TITLE
Running a script part of Rstudio Project and has spaces in its location

### ISSUE THREAD

**Issue by msgoussi** [bnosac/taskscheduleR#74] opened 2020-03-19 11:32 UTC
Dear Mr. Jan,
I am trying to use your package, but I failed to run the script because of two things
1) the location of file has spaces, I can not edit the folder location because I do not have admin rights (i am using windows)
2) how to run a script part of Rstudio Project I have tried reading https://community.rstudio.com/t/how-to-play-nice-with-taskscheduler-r-studio-projects-and-here/24406 but i could not get it properly.

Please advise, with example.

**Comment by jwijffels** [comment] 2020-03-19 11:39
Please provide reproducible examples. Statements like 'it does not work' will not get you any further

**Comment by msgoussi** [comment] 2020-03-19 12:21
I have script called Trial.R inside RStudio Project
setwd(rstudioapi::getActiveProject())
source("0. Sources.R") # Another important script inside the Project i can not drop it.
setwd("D:\\temp")
download.file("https://www.imf.org/external/pubs/ft/weo/2019/02/weodata/WEOOct2019all.xls",
              "x.xls", mode = "wb")
# rest of the code

When I use taskscheduleR, it copies Trial.R into D:\R\R-3.6.3\library\taskscheduleR\extdata
and file x.xls has not been downloaded in temp folder.

**Comment by jwijffels** [comment] 2020-03-19 13:42
So where does the scheduling fail?

**Comment by msgoussi** [comment] 2020-03-19 13:52
The file is not downloaded at all.

**Comment by jwijffels** [comment] 2020-03-19 14:14
So the problem is not related to the taskscheduleR package which does the scheduling but in your own R script. 
Why do you think calls to rstudioapi::getActiveProject() will work if your script is not run in RStudio?
Please change all your setwd calls to right paths which exist on your hard drive and where you have access rights to and learn how to work with environment variables.
Same question as https://github.com/bnosac/taskscheduleR/issues/60
Closing.

**Closed by jwijffels** 2020-03-19 14:14 UTC
